apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: duvvurgpython 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: duvvurgpython 
    spec:
      containers:
        - name: duvvurgpython 
          image: grdcontainerregistry.azurecr.io/duvvurgpython
          ports:
          - containerPort: 80