apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: python3 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: python3 
    spec:
      containers:
        - name: python3 
          image: grdcontainerregistry.azurecr.io/python3
          ports:
          - containerPort: 5000